import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Services',
    'nav.contact': 'Contact Us',
    'nav.about': 'About Us',
    'nav.faq': 'FAQ',
    'nav.post_ad': 'Post Ad',
    'nav.admin': 'Admin',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.profile': 'My Profile',
    'nav.logout': 'Logout',
    'nav.signin_register': 'Sign In / Register',
    'hero.title': "Find Anything, Hire Anyone in Kenya",
    'hero.subtitle': "Connecting skilled fundis, local sellers, and digital freelancers with customers across all 47 counties.",
    'hero.search_placeholder': 'What are you looking for?',
    'hero.all_counties': 'All Counties',
    'hero.search_btn': 'Search',
    'hero.nearby_btn': 'Find Sellers Near Me',
    'hero.tagline': "Kenya's #1 Trusted Marketplace",
    'hero.locating': 'Locating...',
    'section.nearby': 'Nearby You',
    'section.nearby_desc': 'Services and products in your immediate area',
    'section.categories': 'Browse Categories',
    'section.categories_desc': 'Explore services and products by category',
    'section.featured': 'Featured Listings',
    'section.featured_desc': 'Handpicked quality services and products',
    'section.how_it_works': 'How HudumaLink Works',
    'section.how_it_works_desc': 'Your journey to safe and reliable transactions starts here',
    'home.how_it_works': 'How HudumaLink Works',
    'home.how_it_works_desc': 'Your journey to safe and reliable transactions starts here',
    'home.step1_title': 'Search & Connect',
    'home.step1_desc': 'Find the service or product you need and chat with the provider directly on our platform.',
    'home.step2_title': 'Secure with Escrow',
    'home.step2_desc': "Pay securely via M-Pesa. We hold the funds in escrow until you're satisfied with the delivery.",
    'home.step3_title': 'Confirm & Release',
    'home.step3_desc': 'Once you receive your item or service, confirm it in the app to release funds to the seller.',
    'home.verified_providers': 'Verified Providers',
    'home.verified_desc': 'We verify identities for your safety.',
    'home.fast_connections': 'Fast Connections',
    'home.fast_desc': 'Connect with sellers in minutes.',
    'home.top_rated': 'Top Rated',
    'home.top_rated_desc': 'Only the best services for you.',
    'home.ready_to_grow': 'Ready to grow your business?',
    'home.ready_to_grow_desc': 'Join thousands of Kenyan entrepreneurs who use HudumaLink to reach more customers and grow their sales.',
    'home.start_selling': 'Start Selling Today',
    'home.view_all': 'View All',
    'home.no_listings': 'No listings found. Be the first to post!',
    'home.km_away': '{distance} km away',
    'how.step1.title': 'Search & Connect',
    'how.step1.desc': 'Find the service or product you need and chat with the provider directly on our platform.',
    'how.step2.title': 'Secure with Escrow',
    'how.step2.desc': "Pay securely via M-Pesa. We hold the funds in escrow until you're satisfied with the delivery.",
    'how.step3.title': 'Confirm & Release',
    'how.step3.desc': 'Once you receive your item or service, confirm it in the app to release funds to the seller.',
    'trust.verified.title': 'Verified Providers',
    'trust.verified.desc': 'We verify identities for your safety.',
    'trust.fast.title': 'Fast Connections',
    'trust.fast.desc': 'Connect with sellers in minutes.',
    'trust.rated.title': 'Top Rated',
    'trust.rated.desc': 'Only the best services for you.',
    'footer.tagline': "Kenya's most trusted digital marketplace for services and products.",
    'footer.quick_links': 'Quick Links',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.welcome_back': 'Welcome Back',
    'auth.create_account': 'Create Account',
    'auth.signin_desc': 'Sign in to access your marketplace',
    'auth.signup_desc': "Join Kenya's biggest digital marketplace",
    'auth.forgot_password': 'Forgot Password?',
    'auth.reset_password': 'Reset Password',
    'auth.reset_desc': "Enter your email address and we'll send you a link to reset your password.",
    'auth.send_reset': 'Send Reset Link',
    'auth.back_to_signin': 'Back to Sign In',
    'profile.complete_banner': 'Complete Your Profile!',
    'profile.complete_desc': 'Add your demographic information to help us personalize your experience and build trust.',
    'profile.complete_btn': 'Complete Profile',
    'profile.title': 'My Profile',
    'profile.edit_profile': 'Edit Profile',
    'profile.save_changes': 'Save Changes',
    'profile.display_name': 'Display Name',
    'profile.phone_number': 'Phone Number',
    'profile.county': 'County',
    'profile.town': 'Town',
    'profile.dob': 'Date of Birth',
    'profile.gender': 'Gender',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.other': 'Other',
    'profile.county_of_birth': 'County of Birth',
    'profile.occupation': 'Occupation',
    'profile.residence': 'Residence (Area)',
    'profile.residence_info': 'Detailed Residence Info',
    'profile.use_location': 'Use My Current Location for Proximity Search',
    'profile.location_captured': 'Location Captured ✓',
    'profile.location_help': 'Providing your location helps us recommend sellers and services closer to you.',
    'profile.become_provider': 'Become Provider/Seller',
    'profile.view_analytics': 'View Seller Analytics',
    'profile.escrow_balance': 'Escrow Balance',
    'profile.referral_earnings': 'Referral Earnings',
    'profile.referral_code': 'Referral Code',
    'profile.withdraw': 'Withdraw',
    'profile.kyc_status': 'Identity Verification',
    'profile.kyc_verified': 'Verified',
    'profile.kyc_pending': 'Pending',
    'profile.kyc_rejected': 'Rejected',
    'profile.kyc_not_verified': 'Not Verified',
    'profile.kyc_verify_now': 'Verify Identity Now',
    'profile.kyc_banner_title': 'Get Verified Today!',
    'profile.kyc_banner_desc': 'Verified providers get {count}x more inquiries and can post unlimited listings.',
    'profile.my_listings': 'My Listings',
    'profile.post_new': '+ Post New Listing',
    'profile.no_listings': "You haven't posted any listings yet.",
    'profile.mark_sold': 'Mark Sold',
    'profile.promote': 'Promote',
    'profile.delete_confirm': 'Are you sure you want to delete this listing?',
    'profile.reviews_ratings': 'Reviews & Ratings',
    'profile.no_reviews': 'No reviews yet. Complete transactions to build your reputation!',
    'profile.my_orders': 'My Orders & Tracking',
    'profile.order_id': 'Order #{id}',
    'profile.amount': 'Amount',
    'profile.milestone_progress': 'Milestone Progress',
    'profile.withdraw_title': 'Withdraw Funds',
    'profile.withdraw_amount': 'Amount to Withdraw',
    'profile.withdraw_method': 'Withdrawal Method',
    'profile.withdraw_mpesa': 'M-Pesa',
    'profile.withdraw_bank': 'Bank Transfer',
    'profile.withdraw_fee': 'Withdrawal Fee',
    'profile.withdraw_total': 'Total to Deduct',
    'profile.withdraw_btn': 'Submit Withdrawal Request',
    'profile.insufficient_balance': 'Insufficient balance. You need {amount} (including {fee} fee)',
    'profile.min_withdraw': 'Minimum withdrawal is KES 100',
    'profile.verification_progress': 'Verification Progress',
    'profile.verification_help': 'Complete 5 payments to be eligible for verification by an admin.',
    'profile.give_up_provider': 'Give Up Being Provider',
    'profile.give_up_title': 'Are you sure you want to give up being a provider?',
    'profile.give_up_desc': 'Your account will be converted back to a customer account. You will no longer be able to post listings or offer services.',
    'profile.give_up_reason': 'Why are you quitting? (Optional)',
    'profile.give_up_consent': 'I understand that I am giving up my provider status and my listings will be hidden.',
    'profile.become_provider_title': 'Become a Provider',
    'profile.become_provider_confirm': 'Are you sure you want to become a provider?',
    'profile.become_provider_terms': 'I have read and agree to the {terms}',
    'profile.terms_link': 'Terms and Conditions',
    'common.loading': 'Loading...',
    'common.processing': 'Processing...',
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.all': 'All',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort by',
    'common.no_results': 'No results found',
    'common.load_more': 'Load More',
    'common.confirm': 'Confirm',
    'listings.filters': 'Filters',
    'listings.location': 'Location',
    'listings.clear': 'Clear',
    'listings.all_counties': 'All Counties',
    'listings.category': 'Category',
    'listings.all_categories': 'All Categories',
    'listings.price_range': 'Price Range (KES)',
    'listings.min': 'MIN',
    'listings.max': 'MAX',
    'listings.type': 'Listing Type',
    'listings.all_types': 'All Types',
    'listings.products_only': 'Products Only',
    'listings.services_only': 'Services Only',
    'listings.reset_filters': 'Reset All Filters',
    'listings.search_placeholder': 'Search listings...',
    'listings.showing_results': 'Showing {count} results',
    'listings.sort_by': 'Sort by',
    'listings.sort_newest': 'Newest First',
    'listings.sort_price_low': 'Price: Low to High',
    'listings.sort_price_high': 'Price: High to Low',
    'listings.sort_distance': 'Nearest to Me',
    'listings.enable_location': 'Enable Location',
    'listings.locating': 'Locating...',
    'listings.no_listings': 'No matching listings found',
    'listings.no_listings_desc': "We couldn't find anything matching your current filters. Try broadening your search or clearing some filters.",
    'listings.post_listing': 'Post a Listing',
    'listings.popular_categories': 'Popular Categories',
    'listings.in_stock': 'IN STOCK',
    'listings.out_of_stock': 'OUT OF STOCK',
    'listings.contact_price': 'Contact for Price',
    'listing.back': 'Back',
    'listing.under_review': 'This listing is currently under review by our team. It will be visible to everyone once approved.',
    'listing.share': 'Share Listing',
    'listing.report': 'Report Listing',
    'listing.promoted': 'PROMOTED',
    'listing.posted': 'Posted',
    'listing.promote_cta': 'Promote this listing to get more views',
    'listing.promotion_until': 'Promotion active until',
    'listing.availability': 'Availability',
    'listing.units_left': '{count} units left',
    'listing.out_of_stock': 'Out of stock',
    'listing.available_sizes': 'Available Sizes',
    'listing.specifications': 'Specifications',
    'listing.description': 'Description',
    'listing.reviews': 'Reviews & Ratings',
    'listing.leave_review': 'Leave a Review',
    'listing.review_placeholder': 'Share your experience with this seller...',
    'listing.submit_review': 'Submit Review',
    'listing.review_restriction': 'Only buyers who have completed a transaction can leave a review.',
    'listing.no_reviews': 'No reviews yet. Be the first to review!',
    'listing.seller_info': 'Seller Information',
    'listing.transaction_status': 'Transaction Status',
    'listing.payment_pending': 'Payment is pending...',
    'listing.funds_safe': 'Funds are safe in Escrow',
    'listing.completed': 'Transaction Completed',
    'listing.disputed': 'Transaction in Dispute',
    'listing.safety_warning': 'STRICT SAFETY WARNING',
    'listing.safety_warning_desc': 'NEVER pay outside HudumaLink. We are NOT LIABLE for any losses if you pay via M-Pesa directly or cash. Payment outside the platform VOIDS your buyer protection and escrow security.',
    'listing.sandbox_mode': 'Sandbox Mode',
    'listing.sandbox_desc': 'Payments are currently in simulation mode for MVP testing. No real funds will be deducted from your M-Pesa.',
    'listing.buy_escrow': 'Buy via Escrow',
    'listing.hire_escrow': 'Hire via Escrow',
    'listing.terms_agree': 'By clicking above, you agree to our {terms}. Your payment is held securely in Escrow until you confirm delivery.',
    'listing.confirm_delivery': 'Confirm Delivery & Release Funds',
    'listing.raise_dispute': 'Raise a Dispute',
    'listing.call': 'Call',
    'listing.chat': 'Chat',
    'listing.whatsapp': 'WhatsApp Chat',
    'listing.boost': 'Boost Visibility',
    'listing.manage': 'Manage Listing',
    'listing.safety_tips': 'Safety Tips',
    'listing.safety_tip_1': 'Meet in a safe public place for physical items.',
    'listing.safety_tip_2': 'Avoid direct M-Pesa payments to sellers.',
    'listing.safety_tip_3': 'Inspect the item or service before releasing funds.',
    'listing.safety_tip_4': 'Check the seller\'s profile, ratings, and KYC status.',
    'listing.view_safety': 'View Full Safety Guide',
    'listing.report_title': 'Report Listing',
    'listing.report_reason': 'Reason for reporting',
    'listing.select_reason': 'Select a reason',
    'listing.scam': 'Scam or Fraud',
    'listing.prohibited': 'Prohibited Item',
    'listing.misleading': 'Misleading Information',
    'listing.duplicate': 'Duplicate Listing',
    'listing.offensive': 'Offensive Content',
    'listing.other': 'Other',
    'listing.additional_details': 'Additional Details (Optional)',
    'listing.report_placeholder': 'Provide more information to help our moderators...',
    'listing.submit_report': 'Submit Report',
    'listing.dispute_title': 'Raise Dispute',
    'listing.dispute_reason': 'Reason for dispute',
    'listing.not_received': 'Item not received',
    'listing.not_as_described': 'Item not as described',
    'listing.poor_quality': 'Poor service quality',
    'listing.incomplete': 'Incomplete work',
    'listing.upload_evidence': 'Upload Evidence (Optional)',
    'listing.upload_desc': 'Upload photos or videos to support your dispute.',
    'listing.cancel_title': 'Cancel Order',
    'listing.cancel_warning': 'Warning: Cancelling orders frequently may lead to account penalties. Please provide a valid reason.',
    'listing.cancel_reason': 'Reason for cancellation',
    'listing.change_mind': 'Changed my mind',
    'listing.better_price': 'Found a better price',
    'listing.no_response': 'Seller not responding',
    'listing.delivery_delay': 'Delivery delay',
    'listing.confirm_cancel': 'Confirm Cancellation',
  },
  sw: {
    'nav.home': 'Nyumbani',
    'nav.marketplace': 'Sokoni',
    'nav.services': 'Huduma',
    'nav.contact': 'Wasiliana Nasi',
    'nav.about': 'Kuhusu Sisi',
    'nav.faq': 'Maswali',
    'nav.post_ad': 'Weka Tangazo',
    'nav.admin': 'Usimamizi',
    'nav.messages': 'Ujumbe',
    'nav.notifications': 'Arifa',
    'nav.profile': 'Profaili Yangu',
    'nav.logout': 'Ondoka',
    'nav.signin_register': 'Ingia / Jisajili',
    'hero.tagline': "Soko #1 Linaloaminika nchini Kenya",
    'hero.title': 'Soko Linaloaminika Zaidi nchini Kenya',
    'hero.subtitle': 'Nunua, uza, na ajiri kwa kujiamini ukitumia mfumo wetu salama wa Escrow. Pesa zako ziko salama hadi utakapofurahishwa.',
    'hero.search_placeholder': 'Unatafuta nini leo?',
    'hero.all_counties': 'Kaunti Zote',
    'hero.search_btn': 'Tafuta',
    'hero.nearby_btn': 'Tafuta Karibu',
    'hero.locating': 'Inatafuta...',
    'section.nearby': 'Karibu na Wewe',
    'section.nearby_desc': 'Gundua ofa na huduma nzuri katika mazingira yako',
    'section.categories': 'Vinjari kwa Kategoria',
    'section.categories_desc': 'Pata kile unachohitaji kutoka kwa kategoria zetu mbalimbali',
    'section.featured': 'Matangazo Yaliyoangaziwa',
    'section.featured_desc': 'Matangazo bora yaliyochaguliwa kutoka kwa wauzaji wetu wanaoaminika zaidi',
    'home.how_it_works': 'Jinsi HudumaLink Inavyofanya Kazi',
    'home.how_it_works_desc': 'Safari yako ya miamala salama na ya kuaminika inaanzia hapa',
    'home.step1_title': 'Tafuta na Unganisha',
    'home.step1_desc': 'Pata huduma au bidhaa unayohitaji na uongee na mtoa huduma moja kwa moja kwenye jukwaa letu.',
    'home.step2_title': 'Salama na Escrow',
    'home.step2_desc': 'Lipia kwa usalama kupitia M-Pesa. Tunashikilia pesa kwenye escrow hadi utakapofurahishwa na uwasilishaji.',
    'home.step3_title': 'Thibitisha na Achia',
    'home.step3_desc': 'Mara tu unapopokea bidhaa au huduma yako, thibitisha kwenye programu ili kuachia pesa kwa muuzaji.',
    'home.verified_providers': 'Watoa Huduma Waliothibitishwa',
    'home.verified_desc': 'Tunathibitisha vitambulisho kwa ajili ya usalama wako.',
    'home.fast_connections': 'Uunganishaji wa Haraka',
    'home.fast_desc': 'Ungana na wauzaji ndani ya dakika chache.',
    'home.top_rated': 'Waliokadiriwa Juu',
    'home.top_rated_desc': 'Huduma bora pekee kwa ajili yako.',
    'home.ready_to_grow': 'Uko tayari kukuza biashara yako?',
    'home.ready_to_grow_desc': 'Jiunge na maelfu ya wajasiriamali wa Kenya wanaotumia HudumaLink kuwafikia wateja wengi zaidi na kukuza mauzo yao.',
    'home.start_selling': 'Anza Kuuza Leo',
    'home.view_all': 'Tazama Yote',
    'home.no_listings': 'Hakuna matangazo yaliyopatikana. Kuwa wa kwanza kuweka!',
    'home.km_away': 'umbali wa km {distance}',
    'profile.title': 'Wasifu Wangu',
    'profile.edit_profile': 'Hariri Wasifu',
    'profile.save_changes': 'Hifadhi Mabadiliko',
    'profile.display_name': 'Jina la Kuonyesha',
    'profile.phone_number': 'Namba ya Simu',
    'profile.county': 'Kaunti',
    'profile.town': 'Mji',
    'profile.dob': 'Tarehe ya Kuzaliwa',
    'profile.gender': 'Jinsia',
    'profile.male': 'Mume',
    'profile.female': 'Mke',
    'profile.other': 'Nyingine',
    'profile.county_of_birth': 'Kaunti ya Kuzaliwa',
    'profile.occupation': 'Kazi',
    'profile.residence': 'Makazi (Eneo)',
    'profile.residence_info': 'Maelezo ya Kina ya Makazi',
    'profile.use_location': 'Tumia Mahali Pangu kwa Utafutaji wa Karibu',
    'profile.location_captured': 'Mahali Pamepatikana ✓',
    'profile.location_help': 'Kutoa mahali pako hutusaidia kupendekeza wauzaji na huduma karibu nawe.',
    'profile.become_provider': 'Kuwa Mtoa Huduma/Muuzaji',
    'profile.view_analytics': 'Tazama Takwimu za Muuzaji',
    'profile.escrow_balance': 'Salio la Escrow',
    'profile.referral_earnings': 'Mapato ya Rufaa',
    'profile.referral_code': 'Nambari ya Rufaa',
    'profile.withdraw': 'Toa Pesa',
    'profile.kyc_status': 'Uthibitishaji wa Kitambulisho',
    'profile.kyc_verified': 'Imethibitishwa',
    'profile.kyc_pending': 'Inasubiri',
    'profile.kyc_rejected': 'Imekataliwa',
    'profile.kyc_not_verified': 'Haijathibitishwa',
    'profile.kyc_verify_now': 'Thibitisha Kitambulisho Sasa',
    'profile.kyc_banner_title': 'Thibitishwa Leo!',
    'profile.kyc_banner_desc': 'Watoa huduma waliothibitishwa hupata maswali mara {count} zaidi na wanaweza kuweka matangazo bila kikomo.',
    'profile.my_listings': 'Matangazo Yangu',
    'profile.post_new': '+ Weka Tangazo Jipya',
    'profile.no_listings': 'Bado hujaweka matangazo yoyote.',
    'profile.mark_sold': 'Weka kama Imeuzwa',
    'profile.promote': 'Pandisha',
    'profile.delete_confirm': 'Je, una uhakika unataka kufuta tangazo hili?',
    'profile.reviews_ratings': 'Mapitio na Ukadiriaji',
    'profile.no_reviews': 'Bado hakuna mapitio. Kamilisha miamala ili kujenga sifa yako!',
    'profile.my_orders': 'Maagizo Yangu na Ufuatiliaji',
    'profile.order_id': 'Agizo #{id}',
    'profile.amount': 'Kiasi',
    'profile.milestone_progress': 'Maendeleo ya Hatua',
    'profile.withdraw_title': 'Toa Pesa',
    'profile.withdraw_amount': 'Kiasi cha Kutoa',
    'profile.withdraw_method': 'Njia ya Kutoa',
    'profile.withdraw_mpesa': 'M-Pesa',
    'profile.withdraw_bank': 'Uhamisho wa Benki',
    'profile.withdraw_fee': 'Ada ya Kutoa',
    'profile.withdraw_total': 'Jumla ya Kukatwa',
    'profile.withdraw_btn': 'Tuma Ombi la Kutoa Pesa',
    'profile.insufficient_balance': 'Salio halitoshi. Unahitaji {amount} (pamoja na ada ya {fee})',
    'profile.min_withdraw': 'Kiwango cha chini cha kutoa ni KES 100',
    'profile.verification_progress': 'Maendeleo ya Uthibitishaji',
    'profile.verification_help': 'Kamilisha malipo 5 ili uweze kustahili kuthibitishwa na msimamizi.',
    'profile.give_up_provider': 'Acha Kuwa Mtoa Huduma',
    'profile.give_up_title': 'Je, una uhakika unataka kuacha kuwa mtoa huduma?',
    'profile.give_up_desc': 'Akaunti yako itarudishwa kuwa akaunti ya mteja. Hautaweza tena kuweka matangazo au kutoa huduma.',
    'profile.give_up_reason': 'Kwa nini unaacha? (Hiari)',
    'profile.give_up_consent': 'Naelewa kuwa naacha hali yangu ya kuwa mtoa huduma na matangazo yangu yatafichwa.',
    'profile.become_provider_title': 'Kuwa Mtoa Huduma',
    'profile.become_provider_confirm': 'Je, una uhakika unataka kuwa mtoa huduma?',
    'profile.become_provider_terms': 'Nimesoma na kukubaliana na {terms}',
    'profile.terms_link': 'Vigezo na Masharti',
    'footer.tagline': "Soko la kidijitali linaloaminika zaidi nchini Kenya kwa huduma na bidhaa.",
    'footer.quick_links': 'Viungo vya Haraka',
    'footer.support': 'Usaidizi',
    'footer.contact': 'Mawasiliano',
    'auth.login': 'Ingia',
    'auth.signup': 'Jisajili',
    'auth.welcome_back': 'Karibu Tena',
    'auth.create_account': 'Fungua Akaunti',
    'auth.signin_desc': 'Ingia ili kufikia soko lako',
    'auth.signup_desc': 'Jiunge na soko kubwa zaidi la kidijitali nchini Kenya',
    'auth.forgot_password': 'Umesahau Nywila?',
    'auth.reset_password': 'Badilisha Nywila',
    'auth.reset_desc': 'Ingiza barua pepe yako na tutakutumia kiungo cha kubadilisha nywila yako.',
    'auth.send_reset': 'Tuma Kiungo cha Kubadilisha',
    'auth.back_to_signin': 'Rudi Kwenye Kuingia',
    'profile.complete_banner': 'Kamilisha Profaili Yako!',
    'profile.complete_desc': 'Ongeza maelezo yako ya kidemografia ili kutusaidia kubinafsisha uzoefu wako na kujenga uaminifu.',
    'profile.complete_btn': 'Kamilisha Profaili',
    'common.loading': 'Inapakia...',
    'common.processing': 'Inashughulikia...',
    'common.save': 'Hifadhi Mabadiliko',
    'common.cancel': 'Ghairi',
    'common.edit': 'Hariri',
    'common.delete': 'Futa',
    'common.view': 'Angalia',
    'common.all': 'Zote',
    'common.search': 'Tafuta',
    'common.filter': 'Chuja',
    'common.sort': 'Panga kwa',
    'common.no_results': 'Hakuna matokeo yaliyopatikana',
    'common.load_more': 'Pakia Zaidi',
    'common.confirm': 'Thibitisha',
    'listings.filters': 'Vichujio',
    'listings.location': 'Mahali',
    'listings.clear': 'Futa',
    'listings.all_counties': 'Kaunti Zote',
    'listings.category': 'Kitengo',
    'listings.all_categories': 'Vitengo Vyote',
    'listings.price_range': 'Kiwango cha Bei (KES)',
    'listings.min': 'MIN',
    'listings.max': 'MAX',
    'listings.type': 'Aina ya Tangazo',
    'listings.all_types': 'Aina Zote',
    'listings.products_only': 'Bidhaa Pekee',
    'listings.services_only': 'Huduma Pekee',
    'listings.reset_filters': 'Weka Upya Vichujio Vyote',
    'listings.search_placeholder': 'Tafuta matangazo...',
    'listings.showing_results': 'Inaonyesha matokeo {count}',
    'listings.sort_by': 'Panga kwa',
    'listings.sort_newest': 'Mpya Zaidi',
    'listings.sort_price_low': 'Bei: Chini hadi Juu',
    'listings.sort_price_high': 'Bei: Juu hadi Chini',
    'listings.sort_distance': 'Karibu Nami Zaidi',
    'listings.enable_location': 'Washa Mahali',
    'listings.locating': 'Inatafuta...',
    'listings.no_listings': 'Hakuna matangazo yanayolingana yaliyopatikana',
    'listings.no_listings_desc': 'Hatukuweza kupata chochote kinacholingana na vichujio vyako vya sasa. Jaribu kupanua utafutaji wako au kufuta baadhi ya vichujio.',
    'listings.post_listing': 'Weka Tangazo',
    'listings.popular_categories': 'Vitengo Maarufu',
    'listings.in_stock': 'IPO STOKINI',
    'listings.out_of_stock': 'IMEISHA STOKINI',
    'listings.contact_price': 'Wasiliana kwa Bei',
    'listing.back': 'Nyuma',
    'listing.under_review': 'Tangazo hili kwa sasa linakaguliwa na timu yetu. Litaonekana kwa kila mtu likishaidhinishwa.',
    'listing.share': 'Shiriki Tangazo',
    'listing.report': 'Ripoti Tangazo',
    'listing.promoted': 'LIMEPANDISHWA',
    'listing.posted': 'Iliwekwa',
    'listing.promote_cta': 'Pandisha tangazo hili ili kupata watazamaji zaidi',
    'listing.promotion_until': 'Upandishaji unatumika hadi',
    'listing.availability': 'Upatikanaji',
    'listing.units_left': 'zimesalia units {count}',
    'listing.out_of_stock': 'Imeisha stokini',
    'listing.available_sizes': 'Saizi Zinazopatikana',
    'listing.specifications': 'Vipimo',
    'listing.description': 'Maelezo',
    'listing.reviews': 'Mapitio na Ukadiriaji',
    'listing.leave_review': 'Acha Mapitio',
    'listing.review_placeholder': 'Shiriki uzoefu wako na muuzaji huyu...',
    'listing.submit_review': 'Tuma Mapitio',
    'listing.review_restriction': 'Wanunuzi tu ambao wamekamilisha muamala wanaweza kuacha mapitio.',
    'listing.no_reviews': 'Bado hakuna mapitio. Kuwa wa kwanza kukagua!',
    'listing.seller_info': 'Taarifa za Muuzaji',
    'listing.transaction_status': 'Hali ya Muamala',
    'listing.payment_pending': 'Malipo yanasubiriwa...',
    'listing.funds_safe': 'Pesa ziko salama kwenye Escrow',
    'listing.completed': 'Muamala Umekamilika',
    'listing.disputed': 'Muamala una Mgogoro',
    'listing.safety_warning': 'ONYO KALI LA USALAMA',
    'listing.safety_warning_desc': 'USILIPIE nje ya HudumaLink. Hatutawajibika kwa hasara yoyote ukilipa kupitia M-Pesa moja kwa moja au pesa taslimu. Malipo nje ya jukwaa YANAFUTA ulinzi wako wa mnunuzi na usalama wa escrow.',
    'listing.sandbox_mode': 'Hali ya Sandbox',
    'listing.sandbox_desc': 'Malipo kwa sasa yako katika hali ya uigaji kwa ajili ya majaribio ya MVP. Hakuna pesa halisi zitakatwa kutoka kwa M-Pesa yako.',
    'listing.buy_escrow': 'Nunua kupitia Escrow',
    'listing.hire_escrow': 'Ajiri kupitia Escrow',
    'listing.terms_agree': 'Kwa kubofya hapo juu, unakubaliana na {terms} zetu. Malipo yako yanashikiliwa kwa usalama kwenye Escrow hadi utakapothibitisha uwasilishaji.',
    'listing.confirm_delivery': 'Thibitisha Uwasilishaji na Achia Pesa',
    'listing.raise_dispute': 'Anzisha Mgogoro',
    'listing.call': 'Piga Simu',
    'listing.chat': 'Ongea',
    'listing.whatsapp': 'Ongea kupitia WhatsApp',
    'listing.boost': 'Ongeza Mwonekano',
    'listing.manage': 'Simamia Tangazo',
    'listing.safety_tips': 'Vidokezo vya Usalama',
    'listing.safety_tip_1': 'Kutana katika mahali salama pa umma kwa bidhaa za kimwili.',
    'listing.safety_tip_2': 'Epuka malipo ya moja kwa moja ya M-Pesa kwa wauzaji.',
    'listing.safety_tip_3': 'Kagua bidhaa au huduma kabla ya kuachia pesa.',
    'listing.safety_tip_4': 'Angalia wasifu wa muuzaji, ukadiriaji, na hali ya KYC.',
    'listing.view_safety': 'Tazama Mwongozo Kamili wa Usalama',
    'listing.report_title': 'Ripoti Tangazo',
    'listing.report_reason': 'Sababu ya kuripoti',
    'listing.select_reason': 'Chagua sababu',
    'listing.scam': 'Utapeli au Udanganyifu',
    'listing.prohibited': 'Bidhaa Iliyopigwa Marufuku',
    'listing.misleading': 'Taarifa Zinazopotosha',
    'listing.duplicate': 'Tangazo la Marudiano',
    'listing.offensive': 'Maudhui Yanayoudhi',
    'listing.other': 'Nyingine',
    'listing.additional_details': 'Maelezo ya Ziada (Hiari)',
    'listing.report_placeholder': 'Toa taarifa zaidi ili kusaidia wasimamizi wetu...',
    'listing.submit_report': 'Tuma Ripoti',
    'listing.dispute_title': 'Anzisha Mgogoro',
    'listing.dispute_reason': 'Sababu ya mgogoro',
    'listing.not_received': 'Bidhaa haijapokelewa',
    'listing.not_as_described': 'Bidhaa si kama ilivyoelezwa',
    'listing.poor_quality': 'Ubora duni wa huduma',
    'listing.incomplete': 'Kazi haijakamilika',
    'listing.upload_evidence': 'Pakia Ushahidi (Hiari)',
    'listing.upload_desc': 'Pakia picha au video ili kusaidia mgogoro wako.',
    'listing.cancel_title': 'Ghairi Agizo',
    'listing.cancel_warning': 'Onyo: Kughairi maagizo mara kwa mara kunaweza kusababisha adhabu kwenye akaunti. Tafadhali toa sababu halali.',
    'listing.cancel_reason': 'Sababu ya kughairi',
    'listing.change_mind': 'Nimebadili mawazo',
    'listing.better_price': 'Nimepata bei bora zaidi',
    'listing.no_response': 'Muuzaji hajibu',
    'listing.delivery_delay': 'Ucheleweshaji wa uwasilishaji',
    'listing.confirm_cancel': 'Thibitisha Kughairi',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
